
server:
    port: 8765
spring:
    application:
    name: GateWay-Application
    cloud:
    gateway:
        routes:
            - id:Order-Application 
          uri: http://localhost:9090
          predicates:
              - Path=/demo/**

        - id: Payment-Application
          uri: http://localhost:9091
          predicates:
              - Path=/demo/**

            